### ISSUE TITLE
Incapable de charger une table csv

### ISSUE THREAD

**Issue by mchibok** [mchibok/CIV6707A#4]
Salut, j'ai vraiment un problème pour charger les csv.
Il faudrait que vous essayez avec un éditeur de texte et non l'éditeur p5.js pour voir si vous êtes capables de votre bord, parce que là moi je suis incapable d'afficher les arrêts à proximité des marqueurs.

je fais simplement:
`var stops;`
puis
`function preload() {stops = loadTable("gtfs/stops.csv", "csv", "header");}`

Pourtant, la console de firefox me sort toujours: 
<img width="328" alt="ff_erreur" src="https://cloud.githubusercontent.com/assets/25492081/23264776/90c5db86-f9b0-11e6-8f8a-10ec73bab605.PNG">

Mon fichier csv semble pourtant bon: 
<img width="462" alt="stopscsv" src="https://cloud.githubusercontent.com/assets/25492081/23264785/9eac0e64-f9b0-11e6-88cd-461a759728b3.PNG">

Je trouve pas d'aide sur internet.
**HELP!**

@LeaFabre @Laurence344 @valerieCloutier @kaligrafy

**Comment by kaligrafy** [comment]
Je crois qu'il ne peut même pas trouver le fichier. Vérifiez que gtfs/stops.csv est bien dans le dossier depuis lequel vous ouvrez votre fichier html.

**Comment by kaligrafy** [comment]
Je ne vois nulle part dans votre code sur github un dossier qui s'appelle gtfs

**Comment by mchibok** [comment]
bon effectivement, j'avais pas mis le csv sur github car je tentais de faire le tout localement. 
bref, j'ai toujours le même message, mais ça fonctionne parce que je peux afficher les arrêts.
merci!
